services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CarRentalDB  # Make sure this matches your connection string
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - carrental-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: weizedinc/carrental-backend:${TAG:-latest}
    container_name: backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=CarRentalDB;Username=postgres;Password=root
      - Jwt__Secret=${JWT_SECRET:-YOUR_PRODUCTION_SECRET_KEY_SHOULD_BE_AT_LEAST_128_BITS}
      - Jwt__Issuer=${JWT_ISSUER:-http://95.179.252.239:5000}
      - Jwt__Audience=${JWT_AUDIENCE:-http://95.179.252.239}
      - ASPNETCORE_URLS=http://+:8080
      # Dynamic CORS configuration
      - Cors__AllowedOrigins__0=http://95.179.252.239
      - Cors__AllowedOrigins__1=http://localhost:3000
      - Cors__AllowedOrigins__2=http://localhost
      - Cors__AllowedOrigins__3=http://frontend
    volumes:
      - ./uploads:/app/Uploads
      - ./logs:/app/logs
    networks:
      - carrental-network

  frontend:
    image: weizedinc/carrental-frontend:${TAG:-latest}
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - carrental-network

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 backend frontend
    networks:
      - carrental-network

volumes:
  postgres-data:
    driver: local

networks:
  carrental-network:
    driver: bridge